version: '3'

services:

  fastapi:
    container_name: fastapi  # 컨테이너 이름을 지정합니다.
    build:
      context: ./finetune-back
      dockerfile: Dockerfile  # Dockerfile의 경로를 지정합니다. 현재 디렉토리에 있다면 이렇게 지정하면 됩니다.    
    ports: 
      - "8000:80"    
    image: fastapi
  
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - "./conf/nginx/conf.d:/etc/nginx/conf.d"

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email leehyunk6310@naver.com --agree-tos --no-eff-email -d https://k9d109.p.ssafy.io
    volumes:
        - ./conf/certbot/conf:/etc/letsencrypt
        - ./conf/certbot/logs:/var/log/letsencrypt
        - ./conf/certbot/data:/var/www/certbot